
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const UNHELPFULTOKEN = 'UNHELPFULTOKEN';
export const ENTERED = 'ENTERED';
export const VARIABLESAVED = 'VARIABLESAVED';

export const INDICATORSFETCHED = 'INDICATORSFETCHED';
export const INDICATORSCHANGED = 'INDICATORSCHANGED';
export const MULTIPLESPLITCHANGED = 'MULTIPLESPLITCHANGED';

export const ADDSELECTEDPOINT = 'ADDSELECTEDPOINT';
export const REMOVESELECTEDPOINT = 'REMOVESELECTEDPOINT';
export const FORCESELECTEDPOINTS = 'FORCESELECTEDPOINTS';
export const ADDRESSESSELECTIONCHANGED = 'ADDRESSESSELECTION';

export const DATAVIZCHANGED = 'DATAVIZCHANGED';
export const TOOLBOXCHANGED = 'TOOLBOXCHANGED';

export const BOUNDSFETCHED = 'BOUNDSFETCHED';

